version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: temporal-tables-test
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:  
      - 5432:5432